// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleAuth
import GoogleGax
import GoogleShowcaseV1Beta1

enum ShowcaseServerError: Error, CustomStringConvertible {
  case binaryNotFound
  case caCertTimeout
  case readinessTimeout(String)

  var description: String {
    switch self {
    case .binaryNotFound:
      return "gapic-showcase binary not found at GOOGLE_CLOUD_SWIFT_SHOWCASE_PATH"
    case .caCertTimeout:
      return "Timed out waiting for gapic-showcase to write CA certificate"
    case .readinessTimeout(let endpoint):
      return "Timed out waiting for gapic-showcase server at \(endpoint) to be ready"
    }
  }
}

public final class ShowcaseServer: Sendable {
  public let port: Int
  public let fallbackPort: Int
  public let endpoint: String
  public let caCertPEM: String
  private let process: Process

  private init(
    port: Int,
    fallbackPort: Int,
    endpoint: String,
    caCertPEM: String,
    process: Process
  ) {
    self.port = port
    self.fallbackPort = fallbackPort
    self.endpoint = endpoint
    self.caCertPEM = caCertPEM
    self.process = process
  }

  deinit {
    self.stop()
  }

  public func stop() {
    if self.process.isRunning {
      self.process.terminate()
      self.process.waitUntilExit()
    }
  }

  public static func start(
    port: Int = 7471,
    fallbackPort: Int = 1339,
    tlsGroups: String? = "0x11ec"
  ) async throws -> ShowcaseServer {
    let binary = try findBinary()
    let tempCAFile = FileManager.default.temporaryDirectory
      .appendingPathComponent(
        "showcase_ca_\(ProcessInfo.processInfo.processIdentifier)_\(UUID().uuidString).pem")

    let process = Process()
    process.executableURL = URL(fileURLWithPath: binary)
    var args = [
      "run",
      "--port", ":\(port)",
      "--fallback-port", ":\(fallbackPort)",
      "--tls",
      "--ca-cert-output-file", tempCAFile.path,
    ]
    if let tlsGroups {
      args.append(contentsOf: ["--tls-groups", tlsGroups])
    }
    process.arguments = args
    process.standardInput = FileHandle.nullDevice

    let logFile = FileManager.default.temporaryDirectory
      .appendingPathComponent("showcase_\(port).log")
    _ = FileManager.default.createFile(atPath: logFile.path, contents: nil)
    let logHandle = try FileHandle(forWritingTo: logFile)
    process.standardOutput = logHandle
    process.standardError = logHandle

    try process.run()

    // Wait for the autogenerated CA certificate PEM file.
    let caDeadline = Date().addingTimeInterval(30)
    var pemContent: String?
    while Date() < caDeadline {
      if !process.isRunning {
        let errStr = (try? String(contentsOf: logFile, encoding: .utf8)) ?? ""
        throw ShowcaseServerError.readinessTimeout("Showcase process exited early: \(errStr)")
      }
      if FileManager.default.fileExists(atPath: tempCAFile.path),
        let content = try? String(contentsOf: tempCAFile, encoding: .utf8),
        content.contains("-----BEGIN CERTIFICATE-----")
      {
        pemContent = content
        break
      }
      try await Task.sleep(for: .milliseconds(50))
    }

    try? FileManager.default.removeItem(at: tempCAFile)

    guard let caCert = pemContent else {
      process.terminate()
      throw ShowcaseServerError.caCertTimeout
    }

    let endpoint = "https://127.0.0.1:\(port)"
    let server = ShowcaseServer(
      port: port,
      fallbackPort: fallbackPort,
      endpoint: endpoint,
      caCertPEM: caCert,
      process: process
    )

    // Wait until the server is ready by probing with an EchoClient
    try await server.waitUntilReady()
    return server
  }

  private func waitUntilReady() async throws {
    let options = try ClientOptions().with {
      $0.endpoint = self.endpoint
      $0.rootCertificates = self.caCertPEM
      $0.credentials = try Credentials(configuration: .anonymous)
      $0.attemptTimeout = .seconds(5)
      $0.retryPolicy = NeverRetry()
    }
    let client = try EchoClient(options)

    let readyDeadline = Date().addingTimeInterval(30)
    var lastError: (any Error)?
    while Date() < readyDeadline {
      if !self.process.isRunning {
        throw ShowcaseServerError.readinessTimeout(
          "Showcase process terminated unexpectedly: \(lastError.map { "\($0)" } ?? "none")")
      }
      do {
        _ = try await client.echo(
          request: .init().with { $0.response = .content("probe") }
        )
        return
      } catch {
        lastError = error
        try await Task.sleep(for: .milliseconds(100))
      }
    }
    self.stop()
    throw ShowcaseServerError.readinessTimeout(
      "\(self.endpoint), last error: \(lastError.map { "\($0)" } ?? "none")")
  }

  private static func findBinary() throws -> String {
    guard let path = ProcessInfo.processInfo.environment["GOOGLE_CLOUD_SWIFT_SHOWCASE_PATH"],
      FileManager.default.isExecutableFile(atPath: path)
    else {
      throw ShowcaseServerError.binaryNotFound
    }
    return path
  }
}
