# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: User Guide
permissions: read-all # zizmor: ignore[excessive-permissions]
on:
  push:
    branches: [main, 'release-*']
  pull_request:
    branches: [main, 'release-*']
  release:
    types: [published]
jobs:
  guide:
    if: github.repository == 'googleapis/google-cloud-swift'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Install Swift
        uses: ./.github/actions/install-swift
      - name: Build Documentation
        run: |
          set -ev
          args=(
            --transform-for-static-hosting
            --disable-indexing
          )
          declare -A targets=(
            [UserGuide]=guide
            [GoogleCloudWkt]=wkt
            [GoogleCloudGax]=gax
            [GoogleCloudAuth]=auth
            [GoogleCloudStorage]=storage
            [GoogleCloudSecretManagerV1]=google-cloud-secretmanager-v1
          )
          echo DEBBUG DEBUG "${!targets[@]}"
          mkdir -p .render
          for target in "${!targets[@]}"; do
            dir="${target[${target}]}"
            swift package \
              --allow-writing-to-directory .render/${dir} \
              generate-documentation "${args[@]}" \
              --target ${target} \
              --hosting-base-path google-cloud-swift/${target} \
              --output-path .render/${dir}
          done
          # Replace the top-level index file with a redirect, as we only host
          # one target. Otherwise users have to find the hidden directory.
          cat >.render/index.html <<_EOF_
          <!DOCTYPE html>
          <html>
          <head>
              <meta http-equiv="refresh" content="10; url=./UserGuide/documentation/userguide">
          </head>
          <body>
          _EOF_
          for target in "${!targets[@]}"; do
            printf '  <li><a href=\"%s/documentation/%s\">%s</a></li>\n' "${target}" "${target,,}" "${target}" >>.render/index.html
          done
          cat >>.render/index.html <<_EOF_
          </body>
          </html>
          _EOF_
      - name: Upload user guide
        id: deployment
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # ratchet:actions/upload-pages-artifact@v5
        with:
          path: .render
  deploy:
    if: github.repository == 'googleapis/google-cloud-swift' && github.event_name == 'push'
    runs-on: ubuntu-24.04
    permissions:
      # to deploy to Pages
      pages: write
      # to verify the deployment originates from an appropriate source
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: guide
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # ratchet:actions/deploy-pages@v5
